server {
    listen 80;
    listen [::]:80;
    server_name btcloud.work www.btcloud.work;

    root /var/www/btcloud.work;
    index index.html;

    location / {
        try_files $uri $uri/ =404;
    }
}
